CREATE TABLE sys_bug_report (
    id VARCHAR(32) NOT NULL COMMENT '主键',
    organization_id VARCHAR(32) NOT NULL COMMENT '组织id',
    user_id VARCHAR(32) NULL COMMENT '提交人id',
    user_name VARCHAR(64) NULL COMMENT '提交人名称',
    roles VARCHAR(255) NULL COMMENT '角色',
    route VARCHAR(255) NULL COMMENT '页面路由',
    version VARCHAR(64) NULL COMMENT '系统版本',
    user_agent VARCHAR(512) NULL COMMENT '浏览器User-Agent',
    screen VARCHAR(32) NULL COMMENT '屏幕分辨率',
    language VARCHAR(32) NULL COMMENT '语言',
    description TEXT NULL COMMENT '问题描述',
    steps TEXT NULL COMMENT '复现步骤',
    screenshot LONGTEXT NULL COMMENT '截图base64',
    recent_errors TEXT NULL COMMENT '最近错误JSON',
    failed_requests TEXT NULL COMMENT '失败接口JSON',
    trace_id VARCHAR(64) NULL COMMENT '链路追踪ID',
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '状态 PENDING/DONE',
    handle_time BIGINT NULL COMMENT '处理时间',
    handle_user VARCHAR(32) NULL COMMENT '处理人',
    handle_remark VARCHAR(500) NULL COMMENT '处理备注',
    create_time BIGINT NOT NULL COMMENT '提交时间',
    PRIMARY KEY (id),
    KEY idx_org_time (organization_id, create_time)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '问题反馈';
