export const AgentChatStreamUrl = '/agent/chat/stream'; // Agent 对话流式响应
export const AgentChatCancelUrl = '/agent/chat/cancel'; // Agent 取消流式响应
export const AgentChatUrl = '/agent/chat'; // Agent 对话
export const AgentChatConfirmUrl = '/agent/confirm'; // Agent 确认判断问题
export const AgentConversationPageUrl = '/agent-conversation/page'; // 分页获取历史对话列表
export const AgentConversationDetailUrl = '/agent-conversation/get'; // 获取对话消息详情
export const AgentConversationDeleteUrl = '/agent-conversation/delete'; // 删除对话及其全部消息
export const AgentConversationRenameUrl = '/agent-conversation/rename'; // 重命名历史对话: /{conversationId}
export const AgentChatFileUploadUrl = '/agent/chat/file/upload'; // 上传对话文件
export const AgentMcpConfigListUrl = '/agent-mcp-config/list'; // 查询当前用户 MCP 配置列表
export const AgentMcpConfigImportUrl = '/agent-mcp-config/import'; // 导入 MCP 配置文件
export const AgentMcpConfigDeleteUrl = '/agent-mcp-config/delete'; // 删除 MCP 配置
export const SmartDataOverviewUrl = '/smart/data-overview'; // 智慧工作台数据概览
export const SmartDataOverviewRegenerateUrl = '/smart/data-overview/regenerate'; // 数据概览-重新生成
export const SmartAiSummaryUrl = '/smart/ai-summary'; // AI 内容解读-查询
export const SmartAiSummaryRegenerateUrl = '/smart/ai-summary/regenerate'; // AI 内容解读-重新生成
export const AgentActionSuggestionPageUrl = '/agent-action-suggestion/page'; // AI 跟进建议分页查询
export const AgentActionSuggestionIgnoreUrl = '/agent-action-suggestion/ignore'; // 忽略建议
export const AgentActionSuggestionSubmitUrl = '/agent-action-suggestion/submit'; // 提交执行建议
export const AgentActionApprovePageUrl = '/agent-action-approve/page'; // AI 方案审核分页查询
export const AgentActionApproveIgnoreUrl = '/agent-action-approve/ignore'; // 忽略或拒绝审核
export const AgentActionApproveConfirmUrl = '/agent-action-approve/confirm'; // 确认审核并异步提交执行
export const SalesAdvisorAnalyzeUrl = '/agent/advisor/analyze'; // AI 销售会话军师-结构化分析
export const SalesAdvisorAnalyzeStreamUrl = '/agent/advisor/analyze/stream'; // AI 销售会话军师-流式分析
export const AiSalesScriptPageUrl = '/agent/script/page'; // 销售话术库-分页列表
export const AiSalesScriptCategoriesUrl = '/agent/script/categories'; // 销售话术库-分类选项
export const AiSalesScriptAddUrl = '/agent/script/add'; // 销售话术库-新增话术
export const AiSalesScriptUpdateUrl = '/agent/script/update'; // 销售话术库-更新话术
export const AiSalesScriptDeleteUrl = '/agent/script/delete'; // 销售话术库-删除话术（拼 /{id}）
export const AiSalesScriptRetrieveUrl = '/agent/script/retrieve'; // 销售话术库-检索并改写
export const AiSalesScriptImportTemplateUrl = '/agent/script/import/template'; // 销售话术库-下载导入模板
export const AiSalesScriptImportPreCheckUrl = '/agent/script/import/pre-check'; // 销售话术库-导入预校验
export const AiSalesScriptImportUrl = '/agent/script/import'; // 销售话术库-导入
export const AiContentGenerateUrl = '/agent/content/generate'; // AI 获客内容-生成选题/文案/配图文案
export const AiContentGenerateStreamUrl = '/agent/content/generate/stream'; // AI 获客内容-流式生成
export const AiKnowledgeDocPageUrl = '/agent/kb/doc/page'; // 企业知识库-文档分页列表
export const AiKnowledgeDocUploadUrl = '/agent/kb/doc/upload'; // 企业知识库-上传并解析文档
export const AiKnowledgeDocDeleteUrl = '/agent/kb/doc/delete'; // 企业知识库-删除文档（拼 /{id}）
export const AiKnowledgeAskUrl = '/agent/kb/ask'; // 企业知识库-检索问答
export const AiKnowledgeAskStreamUrl = '/agent/kb/ask/stream'; // 企业知识库-流式检索问答
export const AiKnowledgeConfigUrl = '/agent/kb/config'; // 企业知识库-出处片段长度设置（GET 读 / POST 存）
